### ISSUE TITLE
Motor/Sensor Ports, Ratios

### ISSUE THREAD

**Issue by AHaberl** [RoboATV/Pathfinder#4]
- which motor/sensor is connected to which EV3 and port
- motor ratios because of transmissions
- motor speeds
- robot measurements (size, sensor offsets)

**Comment by tobbexiv** [comment]
Brick 1 (Drive):
```
A -> Grab
B -> Drive left
C -> Drive right
D -> Lift Grabber
```
```
1 -> ---
2 -> Light
3 -> ---
4 -> ---
```

Brick 2 (Tower):
```
A -> ---
B -> ---
C -> ---
D -> Turn Tower
```
```
1 -> Camera
2 -> ---
3 -> Compass
4 -> Ultra Sonic
```

**Comment by tobbexiv** [comment]
Transmission:
```
          
56 ---------  ----- 24
                |
              ----- 20
        Motor-|12
```

=> 20/12 * 56/24 = 35/9

**Comment by tobbexiv** [comment]
Updated camera to non-remote. All ports and ratios implemented -> close
